import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Navbar from "@/components/navbar";
import "./globals.css";

const roboto = Roboto({ weight: '400', subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar/>
        <main className="mt-10 p-10 max-w-6xl mx-auto">
          {children}
        </main>
        
      </body>
    </html>
  );
}
